import { z } from 'zod'
import { HeroStudioState } from '@/types/heroStudio.types'

export const heroSidebarSchema = z.object({
	isActive: z.boolean(),
	internalDescription: z.string().max(240),
	badge: z.string().max(80),
	title: z.string().min(1).max(120),
	description: z.string().max(260),
	showBadge: z.boolean(),
	showTitle: z.boolean(),
	showDescription: z.boolean(),
	showCta: z.boolean(),
	ctaText: z.string().max(40),
	ctaLink: z.string().max(240),
	ctaOpenInNewTab: z.boolean(),
	ctaVariant: z.enum(['solid', 'outline', 'ghost']),
	ctaSize: z.enum(['sm', 'md', 'lg']),
	ctaRadius: z.enum(['none', 'sm', 'md', 'lg', 'full']),
	ctaHoverEffect: z.enum(['none', 'lift', 'scale', 'invert']),
	ctaAlignment: z.enum(['left', 'center', 'right']),
	ctaFullWidth: z.boolean(),
	ctaBackgroundColor: z.string(),
	ctaTextColor: z.string(),
	ctaBorderColor: z.string(),
	ctaHoverBackgroundColor: z.string(),
	ctaHoverTextColor: z.string(),
	backgroundImage: z.string().max(2048),
	backgroundImageMobile: z.string().max(2048),
	backgroundVideoUrl: z.string().max(2048),
	contentAlignment: z.enum(['left', 'center', 'right']),
	bannerHeight: z.enum(['normal', 'large', 'fullscreen']),
	overlayOpacity: z.number().min(0).max(100),
	titleColor: z.string(),
	descriptionColor: z.string(),
	badgeColor: z.string(),
	titleFontWeight: z.enum(['bold', 'black', 'outline']),
	linkedDropId: z.string(),
	dropDisplayMode: z.enum([
		'auto',
		'message-only',
		'countdown-only',
		'badge-only',
		'hidden',
	]),
	dropTextAlignment: z.enum(['left', 'center', 'right']),
	dropDateFormat: z.enum(['short', 'long', 'full']),
	dropShowCtaScheduled: z.boolean(),
	dropShowCtaLive: z.boolean(),
	dropShowCtaEnded: z.boolean(),
	dropShowCountdown: z.boolean(),
	dropShowLiveBadge: z.boolean(),
	dropMessageTemplateScheduled: z.string().max(220),
	dropMessageTemplateLive: z.string().max(220),
	dropMessageTemplateEnded: z.string().max(220),
	dropLiveBadgeText: z.string().max(40),
	dropEndedText: z.string().max(40),
	dropCountdownBgColor: z.string(),
	dropCountdownTextColor: z.string(),
	dropLiveBadgeBgColor: z.string(),
	dropLiveBadgeTextColor: z.string(),
	layoutPreset: z
		.enum([
			'editorial-left',
			'centered',
			'product-right',
			'fullbleed-bottom',
		])
		.optional(),
})

export type HeroSidebarFormValues = z.infer<typeof heroSidebarSchema>

export function getSidebarDefaults(
	state: HeroStudioState,
): HeroSidebarFormValues {
	return {
		isActive: state.isActive,
		internalDescription: state.internalDescription,
		badge: state.content.badge,
		title: state.content.title,
		description: state.content.description,
		showBadge: state.content.showBadge,
		showTitle: state.content.showTitle,
		showDescription: state.content.showDescription,
		showCta: state.cta.show,
		ctaText: state.cta.text,
		ctaLink: state.cta.link,
		ctaOpenInNewTab: state.cta.openInNewTab,
		ctaVariant: state.cta.variant,
		ctaSize: state.cta.size,
		ctaRadius: state.cta.radius,
		ctaHoverEffect: state.cta.hoverEffect,
		ctaAlignment: state.cta.alignment,
		ctaFullWidth: state.cta.fullWidth,
		ctaBackgroundColor: state.cta.backgroundColor,
		ctaTextColor: state.cta.textColor,
		ctaBorderColor: state.cta.borderColor,
		ctaHoverBackgroundColor: state.cta.hoverBackgroundColor,
		ctaHoverTextColor: state.cta.hoverTextColor,
		backgroundImage: state.media.backgroundImage,
		backgroundImageMobile: state.media.backgroundImageMobile,
		backgroundVideoUrl: state.media.backgroundVideoUrl,
		contentAlignment: state.layout.contentAlignment,
		bannerHeight: state.layout.bannerHeight,
		overlayOpacity: state.styles.overlayOpacity,
		titleColor: state.styles.titleColor,
		descriptionColor: state.styles.descriptionColor,
		badgeColor: state.styles.badgeColor,
		titleFontWeight: state.styles.titleFontWeight,
		linkedDropId: state.dropConfig.linkedDropId,
		dropDisplayMode: state.dropConfig.dropDisplayMode,
		dropTextAlignment: state.dropConfig.dropTextAlignment,
		dropDateFormat: state.dropConfig.dropDateFormat,
		dropShowCtaScheduled: state.dropConfig.dropShowCtaScheduled,
		dropShowCtaLive: state.dropConfig.dropShowCtaLive,
		dropShowCtaEnded: state.dropConfig.dropShowCtaEnded,
		dropShowCountdown: state.dropConfig.dropShowCountdown,
		dropShowLiveBadge: state.dropConfig.dropShowLiveBadge,
		dropMessageTemplateScheduled:
			state.dropConfig.dropMessageTemplateScheduled,
		dropMessageTemplateLive: state.dropConfig.dropMessageTemplateLive,
		dropMessageTemplateEnded:
			state.dropConfig.dropMessageTemplateEnded,
		dropLiveBadgeText: state.dropConfig.dropLiveBadgeText,
		dropEndedText: state.dropConfig.dropEndedText,
		dropCountdownBgColor: state.dropConfig.dropCountdownBgColor,
		dropCountdownTextColor: state.dropConfig.dropCountdownTextColor,
		dropLiveBadgeBgColor: state.dropConfig.dropLiveBadgeBgColor,
		dropLiveBadgeTextColor: state.dropConfig.dropLiveBadgeTextColor,
		layoutPreset: state.layout.layoutPreset,
	}
}

export type HeroPreset = {
	id: 'streetwear-drop' | 'minimal-fashion' | 'luxury-brand'
	name: string
	description: string
	values: Partial<HeroSidebarFormValues>
}

export const HERO_PRESETS: HeroPreset[] = [
	{
		id: 'streetwear-drop',
		name: 'Streetwear Drop',
		description: 'Alto contraste, urgencia y foco en drop.',
		values: {
			badge: 'DROP EXCLUSIVO',
			title: 'NOCHE DE DROP',
			description: 'Colección limitada. No restock.',
			ctaText: 'ENTRAR AL DROP',
			ctaVariant: 'solid',
			ctaSize: 'lg',
			ctaRadius: 'md',
			ctaHoverEffect: 'lift',
			ctaAlignment: 'left',
			ctaFullWidth: false,
			ctaBackgroundColor: '#E62727',
			ctaTextColor: '#FFFFFF',
			ctaBorderColor: '#E62727',
			ctaHoverBackgroundColor: '#B91C1C',
			ctaHoverTextColor: '#FFFFFF',
			contentAlignment: 'left',
			bannerHeight: 'fullscreen',
			overlayOpacity: 56,
			titleColor: '#FFFFFF',
			descriptionColor: '#E5E7EB',
			badgeColor: '#E62727',
			titleFontWeight: 'black',
			dropDisplayMode: 'auto',
			dropShowCountdown: true,
			dropShowLiveBadge: true,
		},
	},
	{
		id: 'minimal-fashion',
		name: 'Minimal Fashion',
		description: 'Estética limpia con copy editorial.',
		values: {
			badge: 'NEW EDITION',
			title: 'FORMA & CORTE',
			description: 'Siluetas limpias, materiales premium.',
			ctaText: 'EXPLORAR',
			ctaVariant: 'outline',
			ctaSize: 'md',
			ctaRadius: 'full',
			ctaHoverEffect: 'invert',
			ctaAlignment: 'center',
			ctaFullWidth: false,
			ctaBackgroundColor: '#FFFFFF',
			ctaTextColor: '#111827',
			ctaBorderColor: '#FFFFFF',
			ctaHoverBackgroundColor: '#111827',
			ctaHoverTextColor: '#FFFFFF',
			contentAlignment: 'center',
			bannerHeight: 'large',
			overlayOpacity: 38,
			titleColor: '#F9FAFB',
			descriptionColor: '#D1D5DB',
			badgeColor: '#A3A3A3',
			titleFontWeight: 'bold',
			dropDisplayMode: 'message-only',
		},
	},
	{
		id: 'luxury-brand',
		name: 'Luxury Brand',
		description: 'Visual refinado con tono premium.',
		values: {
			badge: 'PRIVATE RELEASE',
			title: 'ATELIER 24',
			description: 'Piezas premium para edición cápsula.',
			ctaText: 'VER LOOKBOOK',
			ctaVariant: 'ghost',
			ctaSize: 'md',
			ctaRadius: 'sm',
			ctaHoverEffect: 'scale',
			ctaAlignment: 'right',
			ctaFullWidth: false,
			ctaBackgroundColor: '#111111',
			ctaTextColor: '#FFFFFF',
			ctaBorderColor: '#D4AF37',
			ctaHoverBackgroundColor: '#1F2937',
			ctaHoverTextColor: '#FFFFFF',
			contentAlignment: 'right',
			bannerHeight: 'large',
			overlayOpacity: 62,
			titleColor: '#F8F8F8',
			descriptionColor: '#E4E4E7',
			badgeColor: '#D4AF37',
			titleFontWeight: 'outline',
			dropDisplayMode: 'badge-only',
		},
	},
]
