import type { Product } from '@/lib/store-context'

export const products: Product[] = [
	{
		id: '1',
		name: 'Hoodie Oversize Negro',
		price: 89,
		image: '/black-oversized-streetwear-hoodie-front.jpg',
		images: [
			'/black-oversized-streetwear-hoodie-front.jpg',
			'/black-oversized-streetwear-hoodie-back.jpg',
			'/black-oversized-streetwear-hoodie-detail.jpg',
		],
		sizes: ['S', 'M', 'L', 'XL'],
		stockStatus: 'available',
		category: 'hoodies',
	},
	{
		id: '2',
		name: 'Camiseta Acid Wash',
		price: 45,
		originalPrice: 65,
		image: '/acid-wash-distressed-tshirt-front.jpg',
		images: [
			'/acid-wash-distressed-tshirt-front.jpg',
			'/acid-wash-distressed-tshirt-back.jpg',
			'/placeholder.svg?height=600&width=600',
		],
		sizes: ['S', 'M', 'L'],
		stockStatus: 'low',
		category: 'tees',
	},
	{
		id: '3',
		name: 'Cargo Pants Wide Fit',
		price: 120,
		image: '/wide-fit-cargo-pants-streetwear-front.jpg',
		images: [
			'/wide-fit-cargo-pants-streetwear-front.jpg',
			'/wide-fit-cargo-pants-streetwear-back.jpg',
			'/wide-fit-cargo-pants-pocket-detail.jpg',
		],
		sizes: ['M', 'L', 'XL'],
		stockStatus: 'available',
		category: 'pants',
	},
	{
		id: '4',
		name: 'Bomber Jacket Vintage',
		price: 150,
		image: '/placeholder.svg?height=600&width=600',
		images: [
			'/placeholder.svg?height=600&width=600',
			'/placeholder.svg?height=600&width=600',
			'/placeholder.svg?height=600&width=600',
		],
		sizes: [],
		stockStatus: 'sold_out',
		category: 'jackets',
	},
	{
		id: '5',
		name: 'Beanie Logo Bordado',
		price: 35,
		image: '/black-beanie-embroidered-logo-front.jpg',
		images: [
			'/black-beanie-embroidered-logo-front.jpg',
			'/black-beanie-embroidered-logo-side.jpg',
			'/black-beanie-embroidered-logo-detail.jpg',
		],
		sizes: ['OS'],
		stockStatus: 'low',
		category: 'accessories',
	},
	{
		id: '6',
		name: 'Joggers Essential',
		price: 75,
		originalPrice: 95,
		image: '/placeholder.svg?height=600&width=600',
		images: [
			'/placeholder.svg?height=600&width=600',
			'/placeholder.svg?height=600&width=600',
			'/placeholder.svg?height=600&width=600',
		],
		sizes: ['S', 'M', 'L', 'XL'],
		stockStatus: 'available',
		category: 'pants',
	},
	{
		id: '7',
		name: 'Sudadera Cropped',
		price: 68,
		image: '/cropped-sweatshirt-streetwear-front.jpg',
		images: [
			'/cropped-sweatshirt-streetwear-front.jpg',
			'/cropped-sweatshirt-streetwear-back.jpg',
			'/cropped-sweatshirt-streetwear-detail.jpg',
		],
		sizes: ['XS', 'S', 'M'],
		stockStatus: 'available',
		category: 'hoodies',
	},
	{
		id: '8',
		name: 'Pantalón Leather Effect',
		price: 110,
		image: '/placeholder.svg?height=600&width=600',
		images: [
			'/placeholder.svg?height=600&width=600',
			'/placeholder.svg?height=600&width=600',
			'/placeholder.svg?height=600&width=600',
		],
		sizes: ['S', 'M'],
		stockStatus: 'low',
		category: 'pants',
	},
	{
		id: '9',
		name: 'Tee Oversize Blanca',
		price: 42,
		image: '/placeholder.svg?height=600&width=600',
		images: [
			'/placeholder.svg?height=600&width=600',
			'/placeholder.svg?height=600&width=600',
			'/placeholder.svg?height=600&width=600',
		],
		sizes: ['S', 'M', 'L', 'XL', 'XXL'],
		stockStatus: 'available',
		category: 'tees',
	},
	{
		id: '10',
		name: 'Hoodie Graphic Print',
		price: 98,
		image: '/placeholder.svg?height=600&width=600',
		images: [
			'/placeholder.svg?height=600&width=600',
			'/placeholder.svg?height=600&width=600',
			'/placeholder.svg?height=600&width=600',
		],
		sizes: ['M', 'L'],
		stockStatus: 'low',
		category: 'hoodies',
	},
	{
		id: '11',
		name: 'Shorts Cargo Negro',
		price: 65,
		image: '/placeholder.svg?height=600&width=600',
		images: [
			'/placeholder.svg?height=600&width=600',
			'/placeholder.svg?height=600&width=600',
			'/placeholder.svg?height=600&width=600',
		],
		sizes: [],
		stockStatus: 'sold_out',
		category: 'pants',
	},
	{
		id: '12',
		name: 'Beanie Distressed',
		price: 38,
		originalPrice: 48,
		image: '/placeholder.svg?height=600&width=600',
		images: [
			'/placeholder.svg?height=600&width=600',
			'/placeholder.svg?height=600&width=600',
			'/placeholder.svg?height=600&width=600',
		],
		sizes: ['OS'],
		stockStatus: 'available',
		category: 'accessories',
	},
]

export function getProductById(id: string): Product | undefined {
	return products.find((p) => p.id === id)
}
